Save user_id and input_path into table
metaspace2020/metaspace pull request #1017
Opened 2021-12-20 15:36 UTC by sergii-mamedov

2021-12-20 15:37 UTC, sergii-mamedov commented on metaspace/graphql/src/modules/moldb/controller.ts
> +  user(database): User {
I'm not completely sure of the correctness, I will just comment.

2021-12-24 12:12 UTC, LachlanStuart requested changes
The new `MolecularDB.user` field always returns an error. Here's how to test the graphql API manually:
1. Set up data in your local environment
2. Go to http://localhost:8888/graphql (change the port if needed)
3. On the settings page set `"request.credentials": "include"` so that your browser cookies are used for authentication. You can log in via the web app.
4. Enter a query that includes the new/changed fields, e.g.
```graphql
query {
  molecularDB (databaseId:48) {
    user { id name email }
  }
}
```

Critical changes:
* Fix the graphql schema type of the `user` field
* Make `MolecularDB.user` resolver return a `UserSource` object
* Make sure it runs

2022-01-12 12:53 UTC, LachlanStuart requested changes
Overall it looks much better, but I think these changes are needed:
* Remove `!` non-null assertions in `MolecularDB.user` (mainly to fix the `TypeError` on dbs with a `null` groupId)
* Only return a single item in `MolecularDB.downloadLink` (or justify returning an array)
* Wait for Theo's feedback about whether access controls are needed in `MolecularDB.downloadLink`

2022-01-12 12:53 UTC, LachlanStuart commented on metaspace/graphql/src/modules/moldb/controller.ts
> +  async downloadLink(database) {
Per discussion IRL/in Slack: we should confirm with Theo whether additional authorization is needed here to restrict download access to people in the same group as the database.

2022-01-12 12:53 UTC, LachlanStuart commented on metaspace/graphql/src/modules/moldb/controller.ts
> +  user: async function(database, args: any, ctx): Promise<User|null> {
A tip for working with resolver functions: TypeScript can usually type-check the parameters, but WebStorm/Pycharm often don't understand them and can't give feedback/code suggestions. It makes life a lot easier if you put type annotations on the 1st and 3rd arguments, e.g. `user: async function(database: MolecularDbModel, args: any, ctx: Context)`.

2022-01-12 12:53 UTC, LachlanStuart commented on metaspace/graphql/src/modules/moldb/controller.ts
> +      })
`database.inputPath` appears to save the full path to the exact S3 object. Why does this need to list objects and find the csv files? I'm not aware of any scenario where there would be multiple files for a molDB. It would also be better and easier for the front-end if this function didn't return an array in the JSON.

2022-01-14 12:35 UTC, LachlanStuart commented
This change is still required:

> * Remove ! non-null assertions in MolecularDB.user (mainly to fix the TypeError on dbs with a null groupId)

2022-01-17 09:38 UTC, LachlanStuart approved these changes

2022-01-17 10:33 UTC, merged