Showing  only valid mails on submitter area
metaspace2020/metaspace pull request #1097
Opened 2022-04-13 13:36 UTC by lmacielvieira

### Description

It seems that some old datasets can have submitters with invalid mail fields and submitter data not structured to be displayed in the metadata viewer. So, these cases were treated so It does not look as a bug in the dataset overview page

<img width="394" alt="image" src="https://user-images.githubusercontent.com/35172605/163192602-1eb763e5-ed85-409c-a65f-9c1463b827be.png">

2022-04-13 19:27 UTC, sergii-mamedov requested changes

2022-04-13 19:27 UTC, sergii-mamedov commented on metaspace/webapp/src/modules/Datasets/overview/DatasetOverviewPage.tsx
> +      const re = /^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/
I would not recommend parsing e-mail with regular expressions. Is to open the gates to hell
For example, you cannot catch such an e-mail with this regex: test@mail.google.com

2022-04-13 19:27 UTC, sergii-mamedov commented on metaspace/webapp/src/modules/Datasets/overview/DatasetOverviewPage.tsx
> +                {!group && submitter?.email && isValidMail(submitter?.email)
As far as I understand, you check if the user has a group. If it's not there, then do you show the e-mail? If so, then I don't understand why. I would simply not show anything for users without a group.

2022-04-13 21:44 UTC, lmacielvieira commented on metaspace/webapp/src/modules/Datasets/overview/DatasetOverviewPage.tsx
> +                {!group && submitter?.email && isValidMail(submitter?.email)
I think the email should be displayed, as maybe some user want to contact the submitter regarding the dataset. As if the submitter is not in a group, there would be no way to get it, if not displayed.

2022-04-13 21:47 UTC, lmacielvieira commented on metaspace/webapp/src/modules/Datasets/overview/DatasetOverviewPage.tsx
> +      const re = /^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/
There is a version to check if with all the rules, it is a little bit big though. I just added this to simple ones, as it is already checked the correct way when registering a dataset. This is for the edge cases that we saw on staging where the id is saved on the mail field (probably prior to checking if email is valid on dataset upload)

2022-04-13 21:50 UTC, lmacielvieira commented on metaspace/webapp/src/modules/Datasets/overview/DatasetOverviewPage.tsx
> +      const re = /^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/
also, by the rules, this is a valid mail. It can have up to three fields after @. I.e brazilian mail lucas@uol.com.br (https://help.returnpath.com/hc/en-us/articles/220560587-What-are-the-rules-for-email-address-syntax-)

2022-04-13 22:09 UTC, sergii-mamedov commented on metaspace/webapp/src/modules/Datasets/overview/DatasetOverviewPage.tsx
> +      const re = /^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/
this is valid mail, but this regex `^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$` won't catch him

2022-04-19 11:32 UTC, lmacielvieira commented on metaspace/webapp/src/modules/Datasets/overview/DatasetOverviewPage.tsx
> +                {!group && submitter?.email && isValidMail(submitter?.email)
Email is not being displayed anymore for now. It also solves the last comment

2022-04-19 13:57 UTC, sergii-mamedov approved these changes

2022-04-19 14:25 UTC, merged