Added seriate sorting to spotting axis
metaspace2020/metaspace pull request #1208
Opened 2022-10-12 11:52 UTC by lmacielvieira

### Description

Added seriate sorting to spotting axis, updated interlab file and moved spotting to dockerized lambda #1200

2022-10-14 14:50 UTC, sergii-mamedov requested changes
1. Please add a bash script for creating and uploading docker image on AWS. Example is [here](https://github.com/metaspace2020/metaspace/blob/master/metaspace/engine/docker/lithops_ibm_ce/build_and_push.sh).
2. Please remove or uncomment all commented line.
3. I think it would be good not to use a separate requirements.txt but to do as [here](https://github.com/metaspace2020/metaspace/blob/master/metaspace/engine/docker/lithops_ibm_ce/Dockerfile#L34-L35). But it's up to you.

2022-10-14 14:50 UTC, sergii-mamedov commented on metaspace/engine/lambdas/spotting/Dockerfile
> +FROM  --platform=linux/amd64 public.ecr.aws/lambda/python:3.8
I would use the official python image that we use everywhere

2022-10-14 14:50 UTC, sergii-mamedov commented on metaspace/engine/lambdas/spotting/app.py
> +                fraction = 1
I will be change on this:
```
df = data[(data[y_axis] == row) & (data[x_axis] == col)]['fraction_detected']
fraction = df.values[0] if df.size else 1  # df.size return a number

```

2022-10-17 10:14 UTC, lmacielvieira commented on metaspace/engine/lambdas/spotting/Dockerfile
> +ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
The seriate sorting use a dependence that needs to downgrade protobuf and only works with this env variable value

2022-12-01 11:47 UTC, sergii-mamedov approved these changes

2022-12-01 13:33 UTC, merged