Updated scoring model schema
metaspace2020/metaspace pull request #1513
Opened 2024-04-09 09:41 UTC by lmacielvieira

### Description

Applied pertinent updates to support new ML models and updated scoring model schema to support behavior similar to molecular databases #1491 

*** analysis_version field kept for backwards compatibility

#### How to test it
1 - Run migration
2 - Run metaspace/docker/sm-engine/install-scoring-model.sh script to install ML models
3 - Change old ML model (v3_default) column is_archived to 'true'

<img width="1544" alt="image" src="https://github.com/metaspace2020/metaspace/assets/35172605/73004e18-c36e-41db-beb5-c3f51676c535">
<img width="1356" alt="image" src="https://github.com/metaspace2020/metaspace/assets/35172605/e1dc6dda-ea09-4bb3-a60b-b3b03c8a4c36">
<img width="319" alt="image" src="https://github.com/metaspace2020/metaspace/assets/35172605/071f1201-eae7-49ae-b483-31f380c2842d">

2024-04-11 13:57 UTC, sergii-mamedov requested changes

2024-04-11 13:57 UTC, sergii-mamedov commented on metaspace/engine/sm/engine/annotation_lithops/run_fdr.py
> +    logger.info(ds_config['fdr'].get('scoring_model_version'))
please change it for one line, like
```
logger.info(f'Scoring model: MSM')
or
logger.info(f'Scoring model: {__name__} / {__version__}')
```

2024-04-11 13:57 UTC, sergii-mamedov commented on metaspace/engine/scripts/import_scoring_model.py
> +        parser.add_argument('bucket', type=str, help='S3 or MinIO bucket to upload to')
I think you over complicated the logic a little.
I would not create a `pre_parser` and make the `model_type` argument mandatory. The parameters `model` and `bucket` setting up by default to `None`, and only if `model_type == 'catboost'` would I check for these arguments.

2024-04-11 13:57 UTC, sergii-mamedov commented on metaspace/engine/sm/engine/annotation/scoring_model.py
> +def find_by_id(id_: int) -> ScoringModel:
Do we still need all these functions? `find_original`, `find_by_name_version`, `find_by_id`

2024-04-11 13:57 UTC, sergii-mamedov commented on metaspace/engine/sm/engine/dataset.py
> +        scoring_model = find_by_id(scoring_model_id)
I think it is not needed anymore. Or not?

2024-04-11 13:57 UTC, sergii-mamedov commented on metaspace/engine/sm/fdr_engineering/run_train_eval.py
>  MODEL_NAME = 'v3_default'
It it still relevant?

2024-04-11 15:23 UTC, sergii-mamedov requested changes

2024-04-11 15:23 UTC, sergii-mamedov commented on metaspace/python-client/metaspace/sm_annotation_utils.py
> +            db_name, db_version = scoring_model
please change `db_name`, ... to `model_name` or something like this

2024-04-12 13:54 UTC, lmacielvieira commented on metaspace/engine/sm/engine/dataset.py
> +    # analysis_version kept for compatibility with old datasets and client
I've removed as parameter, but kept the backward compatibility by setting it according to model typ.

2024-04-12 13:54 UTC, lmacielvieira commented on metaspace/engine/sm/engine/annotation_lithops/run_fdr.py
> +    logger.info(ds_config['fdr'].get('scoring_model_version'))
I've removed it.

2024-04-12 13:55 UTC, lmacielvieira commented on metaspace/engine/sm/engine/dataset.py
> +        scoring_model = find_by_id(scoring_model_id)
Removed find_original, but find_by_id is necessary to get model_type as analysis_version parameter was discontinued

2024-04-12 13:58 UTC, lmacielvieira commented on metaspace/engine/sm/fdr_engineering/run_train_eval.py
>  MODEL_NAME = 'v3_default'
Should we ask Bishoy if he still uses to evaluate the model?

2024-04-16 14:49 UTC, sergii-mamedov approved these changes
LGTM

2024-04-16 17:00 UTC, merged