Default projects to private
metaspace2020/metaspace pull request #687
Opened 2020-10-05 17:19 UTC by richardgoater

**Notes on optional 2nd commit:**
Felt that the empty checkbox causes unnecessary worry at point in the process where a user probably needs to write the description and organise datasets before making the project public. A note provides instructions on where/how to find the setting after the project is created.

2020-10-06 11:25 UTC, LachlanStuart approved these changes
There's no blockers, but I feel this could still be better communicated to users so I've left some suggestions in the comments.

2020-10-06 12:12 UTC, richardgoater commented on metaspace/graphql/src/modules/project/model.ts
> -  @Column({ name: 'is_public', type: 'boolean', default: true })
Applying good defaults throughout isn't a bad thing.

2020-10-06 12:32 UTC, richardgoater commented on metaspace/webapp/src/modules/MetadataEditor/__snapshots__/MetadataEditor.spec.ts.snap
> +            </div>
I thought this was supposed to be a review of the code, but that's ok. I'm still hoping for per-PR deployments 🤞 

A switch might be nice, can try that.

2020-10-06 13:22 UTC, LachlanStuart commented on metaspace/webapp/src/modules/MetadataEditor/__snapshots__/MetadataEditor.spec.ts.snap
> +            </div>
> I thought this was supposed to be a review of the code

We use code review for both knowledge sharing and QC. 

On the knowledge sharing side, ideally everybody working on a codebase should at least stay up-to-date with the patterns and architecture of that codebase. Also, at least one other person should understand the change so they can support it if the creator isn't available.

On the QC side, CRs are often the only gate between task allocation and release to production, so really everything that hasn't been previously agreed upon is up for scrutiny. You can't judge visuals from code alone.

2020-10-06 13:22 UTC, richardgoater commented on metaspace/webapp/src/modules/MetadataEditor/__snapshots__/MetadataEditor.spec.ts.snap
> +            </div>
![image](https://user-images.githubusercontent.com/1429721/95206743-f6d1a280-07de-11eb-9b89-1dee4999c220.png)

It looks like this. It's left-aligned to leave space for the help text in the settings page when projects are published.

2020-10-06 13:37 UTC, LachlanStuart commented on metaspace/webapp/src/modules/MetadataEditor/__snapshots__/MetadataEditor.spec.ts.snap
> +            </div>
"Private"/"Public" need to be explained

2020-10-07 09:49 UTC, richardgoater commented on metaspace/webapp/src/modules/MetadataEditor/__snapshots__/MetadataEditor.spec.ts.snap
> +            </div>
I don't think I want to spend more time on this. You're welcome to draft something and push to this branch, otherwise we could leave it as it was and come back to it.

2020-10-07 15:57 UTC, LachlanStuart commented on metaspace/webapp/src/modules/MetadataEditor/__snapshots__/MetadataEditor.spec.ts.snap
> +            </div>
The feedback I've given has frankly been obvious stuff that you should have caught before requesting a review. E.g. the latest revision takes a UI we know to be hard to understand, and removes the explanation, replacing it with opaque terminology - it's a clear usability regression. Please at least do a basic check of your work before you send it out for review. This does not need to be such a high-friction process!

If you don't want to spend time on something, don't rush out a low-quality revision. Defer it until you do have time, or find another solution. It wastes both our time when I have to point out these obvious problems. 

> You're welcome to draft something and push to this branch

It's not my task. Also, sharing branches is bad, as we saw with the tangle of Custom DB UI PRs.

If you aren't prepared to spend time on the bigger UX revision that you started in this PR, then my suggestion would be to start again and just do the one-line fix (+snapshot updates) of changing the checkbox default state to unchecked.

2020-10-07 15:58 UTC, LachlanStuart requested changes
Per the comments, this now has a blocking UX regression.

2020-10-20 15:12 UTC, richardgoater commented
Added some help text:

![image](https://user-images.githubusercontent.com/1429721/96606005-b863d980-12ee-11eb-95f7-f33db7d33d1b.png)

Corresponding update to the settings tab, showing the published project case:

![image](https://user-images.githubusercontent.com/1429721/96606169-e47f5a80-12ee-11eb-961e-e848d12a7ba5.png)

2020-10-22 09:25 UTC, LachlanStuart approved these changes

2020-10-26 09:22 UTC, merged