Feat/dataset overview
metaspace2020/metaspace pull request #806
Opened 2021-03-26 15:14 UTC by lmacielvieira

### Description

In order to improve user experience and better show the dataset specific information, a page that displays relevant dataset information was created. Some actions available on the dataset item card were removed and a link to navigate to the dataset overview page was added

#### Changes

[Front end]

- [ ] Removed admin dataset actions from dataset item card on dataset list page and added a navigation to the Dataset overview page
 Create dataset overview page and route based on dataset id (dataset/:id)

 Create dataset specific information area

 Create dataset gallery viewer area

 Display the dataset title on information area

 Display dataset submitter name on information area

 Display dataset submitter group name and redirect user to group page, when the user user click on group name

 Display dataset description on information area

 Create an annotation component that shows dataset related annotations separated by database and fdr level

 Redirect user to annotation page filtered by dataset/fdr/database when it applies. The applied scenario should happen when the user click on an annotation count on the annotation component or in the 'browse annotation' button

 Display dataset metadata on information area

 Display the dataset related projects on information area

 Add a switch to hide gallery area (needed while there is no backend for gallery features)

 Add a grouped filter to the dataset gallery

 Render a imageloader or a text according to the selected group filter

[Back end]

 Associate a description field to dataset

2021-03-31 15:07 UTC, LachlanStuart requested changes
Overall looks really good, and it's impressive that you got through this so quickly.

The feedback items I consider critical before merging:
* Renaming `datasetDescription` to `description` (it's very painful to rename API fields after release, so it's best to do it now if we do change it)
* Adding a feature flag so that the "Dataset overview" link is hidden by default
* Fixing the Datasets list quick filter
* Changing `MetadataEditor.spec.ts` to use `mount` instead of `shallowMount`

2021-03-31 15:13 UTC, LachlanStuart commented
One more feedback item: I haven't added any specific feedback about the appearance of the Overview page as I feel we should wait until the diagnostics stuff is ready before doing a polishing pass to make it pretty. The main thing I think should be done is updating the typography (header & text styles) to match the new style of the content pages, e.g. [help](https://metaspace2020.eu/help) and [publications](https://metaspace2020.eu/publications). However, this can wait for a future PR.

2021-04-06 08:47 UTC, LachlanStuart approved these changes
The changes look good. You're free to merge this once the CI test/lint has been fixed

2021-04-06 09:15 UTC, lmacielvieira commented on metaspace/webapp/src/modules/Datasets/list/DatasetItemActions.tsx
> +          </div>
Added feat show_dataset_overview.
i.e http://xxxxx/datasets?feat=show_dataset_overview

2021-04-06 09:15 UTC, lmacielvieira commented on metaspace/webapp/src/modules/Annotations/AnnotationsPage.vue
>    <div id="annot-page">
Added back button. (screenshot updated on PR description)

2021-04-06 09:17 UTC, lmacielvieira commented on metaspace/webapp/src/modules/Datasets/overview/AnnotationCountTable.tsx
> +            undefined)}>
It was needed, as I removed the db in "defaultInLevels" for the specific case where annotation is accessed via dataset overview navigation.

2021-04-06 09:18 UTC, merged