Feat/bulk add rem datasets
metaspace2020/metaspace pull request #814
Opened 2021-04-06 09:55 UTC by lmacielvieira

### Description

In order to improve user experience and allow the project managers to bulk add/remove the datasets related to the project, a modal component was created to perform this task.

Issue #807 

#### Changes

##### Front end

###### View project page
- [x] Added "Manage datasets" button on datasets tab
- [x] Added NewFeaturePopup tp manage datasets so the user can note the new feature

###### Project Datasets Dialog Component
- [x] Created component to list datasets for bulk add/remove
- [x] Enable Managers to remove datasets from other users
- [x] Enable Users to add/remove their datasets from the project

***Note
Although there was already a component used to add/remove datasets from projects, as the component created the project itself, and did not enable remove, a new component was created as the main function of the components differ. The new component also was written in ts and with test, so it fits the new project standards. If you understand both components should be one, I can add a few props flags to enable both as one.

##### Graphql

###### Update Dataset projects
- [x] Added asyncEsUpdate flag option to update datasets function 
- [x] Added removedDatasetIds param, in order to receive dataset ids to be removed from project association
- [x] Removed datasetIds as mandatory param, as it is possible to have situations where there are only datasets to be removed. If no datasetIds and no removeDatasetIds is passed, nothing happens.

 
 #### Tests
 
 ##### Front end
 
- [x] Unit Test
- [ ] e2e Test
 
 ###### Browsers and resolutions
- [x] Chrome
- [x]  Safari
- [x] sm, md, lg, xl, lg

<img width="1790" alt="Screenshot 2021-04-06 at 06 36 59" src="https://user-images.githubusercontent.com/35172605/113693276-cfcc2e80-96a4-11eb-9a81-c5c5b9647bf9.png">
<img width="1792" alt="Screenshot 2021-04-06 at 06 35 43" src="https://user-images.githubusercontent.com/35172605/113693300-d5297900-96a4-11eb-9c50-bd7a93a215ab.png">

2021-04-11 15:05 UTC, LachlanStuart requested changes
I hate to be pedantic about coding style, but the handling of nullability in this PR is way too defensive. We already pay a price to use TypeScript and GraphQL schemas, not only are we paying twice if we keep double-checking types everywhere, but it makes the code harder to work with when we revisit it. It adds more code (meaning there's more to read/update later) and also makes it confusing to edit - one has to ask "Why is this being type-checked here? Are there legitimate cases where non-arrays are being passed in this variable that I have to consider?", which makes it a lot more difficult to change if the code isn't familiar.

There are legitimate cases where defensive coding makes sense (ElasticSearch documents, `req` params in Express handler, decoded JSON blobs, untyped 3rd-party libraries, etc.), but the majority of our code has type checking at a framework level (Vue prop type enforcement, GraphQL schema enforcement, TypeScript, SQL/TypeORM schemas) and it's better to rely on that than reimplement it over and over in our own code.

The required feedback items are:
* Overuse of `Array.isArray` and `?.`
* Removing the debug logging (or cleaning it up and promoting it to `logger` calls)
* Removing "admin" terminology when `manager` is intended
* Fixing the two bugs:
  * Only the first 8 non-FAILED datasets in a project can be removed (due to reuse of `projectDatasets`)
  * Some checkboxes get stuck when editing the list a second time (due to dynamically creating properties on a reactive object)

2021-04-14 10:04 UTC, lmacielvieira commented on metaspace/graphql/src/modules/project/operation/updateProjectDatasets.ts
> +    console.log('TO REMOV', datasets.length, JSON.stringify(datasets))
ok, I forgot to remove this one.

2021-04-14 10:06 UTC, lmacielvieira commented on metaspace/graphql/src/modules/project/controller/Mutation.ts
>        }))
Ok, I created a new function "getDatasetFromProjectForEditing" so It can validate this new role for removal and adding the datasets specifically to the importDatasetsIntoProject case

2021-04-14 10:06 UTC, lmacielvieira commented on metaspace/graphql/src/modules/project/controller/Mutation.ts
> +  async importDatasetsIntoProject(source, {
Added one test suit regarding this to the same file "Mutation.membership.spec.ts "

2021-04-14 10:07 UTC, lmacielvieira commented on metaspace/webapp/src/modules/Project/ProjectDatasetsDialog.spec.ts
> +            __typename: 'Dataset',
I just copied the mock from the JSON.stringify actual return, thats why the __typename was included. But now I removed, thx.

2021-04-14 10:08 UTC, lmacielvieira commented on metaspace/webapp/src/modules/Project/ProjectDatasetsDialog.tsx
> +    noDatasetsLabel: { type: String, default: 'No datasets available' },
As discussed via slack, I decided to follow your recommendation and changed it.

2021-04-14 10:08 UTC, lmacielvieira commented on metaspace/webapp/src/modules/Project/ProjectDatasetsDialog.tsx
> +        submitter: props.currentUserId,
Actually it fixed a bug i didnt see before. Where when I changed the users while in the project page, the datasets were not updating. Thx for that tip.

2021-04-16 20:36 UTC, LachlanStuart approved these changes
Generally looks good, however I think the new `allProjectDatasets` resolver should be removed before merging, as `allDatasets` can handle that query without any modification.

2021-04-16 20:36 UTC, LachlanStuart commented on metaspace/graphql/src/modules/dataset/controller/Query.ts
> +  },
This seems to be identical to the `allDatasets` query resolver above, except with different default parameters specified in the schema. It would be preferable to reuse the existing `allDatasets` endpoint and just remove the `limit` by specifying `limit = null` in the client-side GQL query.

2 relevant things about graphql, in case you weren't aware:
* On the client side, you can have many different GQL queries to the same server-side query resolver for different components, with different configurations of parameters & return fields. e.g. the Datasets page uses `datasetDetailItemsQuery` because it needs most dataset fields, but the New Project popup uses `datasetListItemsQuery` because it only needs a few fields and uses very few filters. 
    It's preferable to do it this way, with each component making its own GQL query, so that you can add/remove fields for one component without potentially breaking another component's data source.
* Unlike REST, with GraphQL it's generally better to have fewer queries & mutations, but make them more configurable. The client-side GQL queries add a lot of flexibility so that you can customize the way the queries are used. `allAnnotations` is a great examples of this - it's used differently by different components on the Annotations page, all by using different combinations of input parameters and return fields.

2021-04-16 20:36 UTC, LachlanStuart commented on metaspace/graphql/src/modules/project/operation/updateProjectDatasets.ts
> +    const promises = datasets.map(async(dataset: any) => {
Why did you add `: any` in so many places here? TS should have been able to figure out the type of `datasets` and `dataset.datasetProjects` without any issues...

2021-04-30 13:55 UTC, merged