Removing unnecessary request in python-client
metaspace2020/metaspace pull request #981
Opened 2021-11-05 16:43 UTC by sergii-mamedov

2021-11-05 16:46 UTC, sergii-mamedov commented on metaspace/python-client/metaspace/sm_annotation_utils.py
> +                    bar_format='{l_bar}{bar:40}{r_bar}{bar:-10b}',
Without specifying parameters, the progress bar in Jupyter notebook stretches for one and a half lines. This is not the best solution, but I could not find how to set the width of the center area as a percentage.

2021-11-09 14:02 UTC, LachlanStuart requested changes
Please fix direct calls to `SMDataset.isotope_images`

2021-11-09 14:47 UTC, sergii-mamedov commented on metaspace/python-client/metaspace/sm_annotation_utils.py
> -        )
yep, my mistake, fixed

2021-11-10 13:03 UTC, LachlanStuart approved these changes

2021-11-12 11:07 UTC, merged